### ISSUE TITLE
Restart problem

### ISSUE THREAD

**Issue by semiversus** [makhowastaken/Soft-Latching-Power-Button#1]
I use the same soft latching schematic and I have the same problem when power off and power on after a short time. Do you found a solution? I'll investigate into this issue and will keep you informed.

**Comment by mitchellcairns** [comment]
Y'all could try putting a 1k to 5k resistor between the power line and ground to more instantly drain the system caps. It's like adding that drain resistor earlier in the schematic.

**Comment by semiversus** [comment]
Thanks for your answer. Sounds reasonable. I changed the schematic to fit my usecase. I'm using a microcontroller which should be able to turn the supply of. Here is the result:
![image](https://user-images.githubusercontent.com/5547660/165239139-48d1c989-0c02-45c2-9ad6-a96788fc7863.png)
